# Generated by Django 4.0.4 on 2022-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questons',
            new_name='Question',
        ),
    ]
