# Generated by Django 4.0.4 on 2022-05-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_student_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='City',
        ),
    ]
